
<div id="content_account" class="content_main">

    <?php
    $AccountData = $this->getAccountData();
    extract($AccountData);
    ?>

    <div class="account">
        <h1>ACCOUNT SETTINGS</h1>
       <!-- <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="addon-wrapping">E-mail</span>
            </div>
            <input id="acc_email" name="acc_email" type="email" class="form-control" aria-describedby="basic-addon1" value="<?=$email;?>">
            <button type="submit" class="btn btn-info" onclick="changeEmail(event)">Change</button>
        </div> -->
        <h2>Password Change</h2>
        <form id = "acChangePassForm">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="addon-wrapping">Password</span>
                </div>
                <input id="acc_password" name="acc_password" type="password" class="form-control">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="addon-wrapping">Password repeat</span>
                </div>
                <input id="repeat_acc_password" name="repeat_acc_password" type="password" class="form-control">
                <button type="submit" class="btn btn-info" onclick="changePassword(event)">Change</button>
            </div>
        </form>

    </div>
</div>

<script>
   /* function changeEmail() {

        event.preventDefault();

        if (window.inProgress) {
            return;
        }
        var email = jQuery("#acc_email").val();

        jQuery.ajax({
            url: "/figures_dashboard/dashboard/changeEmail",
            type: "POST",
            data: {email:email},
            beforeSend: function() {
                window.inProgress = true;
            },
            success: function (data) {
                window.inProgress = false;
                if(data.status=="success"){
                    showNotify(data.title, data.message, 'success');
                } else if(data.status=="error"){
                    showNotify(data.title , data.message, 'danger');
                }
            },
            cache: false
        });
    }*/

    function changePassword() {

        event.preventDefault();

        if (window.inProgress) {
            return;
        }
        var formData = jQuery('#acChangePassForm').serializeArray();

        jQuery.ajax({
            url: "/figures_dashboard/dashboard/changePassword",
            type: "POST",
            data: formData,
            beforeSend: function() {
                window.inProgress = true;
            },

            success: function (data) {
                window.inProgress = false;
                if(data.status=="success"){
                    showNotify(data.title, data.message, 'success');
                } else if(data.status=="error"){
                    showNotify(data.title , data.message, 'danger');
                }
            },
            cache: false
        });
    }

</script>