<div id="content_dash" class="content_main">
    <div class="dashboard">
        <h1>Hello, <?php echo $this->getCustomerNickname() ?></h1>
        <div class="row">
            <div class="col-5 dashboard__credit">
                <ul class="list-inline">
                    <li class="dashboard__title">
                        <h2><i class="fas fa-credit-card"></i> Credit</h2>
                        <h3>Since Last Payout</h3>
                    </li>
                    <li><hr></li>
                    <li><h4>USD</h4></li>
                    <li><h5>0.00</h5></li>
                    <li><hr></li>
                    <li><h6>Sales</h6></li>
                    <li><h5>30</h5></li>
                    <li><h6>Items</h6></li>
                    <li><button class="btn btn-info">View more</button></li>
                </ul>
            </div>
            <div class="offset-1 col-5 dashboard__comissions">
                <ul class="list-inline">
                    <li class="dashboard__title">
                        <h2><i class="fas fa-credit-card"></i> Comissions</h2>
                        <select title="select_state" class="form-control" name="state">
                            <option value="AL">Last 30 Days: 21 Aug. - 19 Sep</option>
                        </select>
                    </li>
                    <li><hr></li>
                    <li><h4>USD</h4></li>
                    <li><h5>0.00</h5></li>
                    <li><hr></li>
                    <li><h6>Sales</h6></li>
                    <li><h5>30</h5></li>
                    <li><h6>items</h6></li>
                    <li><button class="btn btn-info">View more</button></li>
                </ul>
            </div>
        </div>
    </div>
</div>