<?php
/** @var $this Figures_Dashboard_Block_Dashboard_DesignManagement */

$designsData = $this->getDesignData();
//echo '<pre>';
//print_r($designsData);
//echo '</pre>';
//die();
?>
<?php if ($designsData) : ?>
    <div id="content_design_management" class="content_main">
        <div class="tools">
        <?php foreach ($designsData as $designItem) : ?>
            <div class="tool row">
                <div class="col-2 tool-img">
                    <ul>
                        <li>
                            <label class="customcheck">
                                <input type="checkbox" checked="checked">
                                <span class="checkmark"></span>
                            </label>
                        </li>
                        <li class="img-full"><img class="float-right" src="<?php echo $designItem['image_path'] ?>"></li>
                    </ul>
                </div>
                <div class="col-2 tool-about">
                    <h2><?php echo $designItem['char_name'] ?></h2>
                    <h3><?php echo $designItem['description'] ?></h3>
                    <ul class="list-inline">
                    <?php foreach (explode(',', $designItem['tags']) as $tag) : ?>
                        <li class="list-inline-item"><?php echo $tag ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
                <div class="col-3 tool-sales">
                    <h2>Sales</h2>
                    <h3><?php echo $designItem['total_count'] ?> times</h3>
                    <br>
                    <h2>Commissions</h2>
                    <h3><?php echo $designItem['total_sum'] ?> USD</h3>
                </div>
                <div class="col-3 tool-products">

                    <?php if ($designItem['product_data']) : ?>
                        <ul>
                            <?php foreach ($designItem['product_data'] as $productItem) : ?>
                            <li><a href="<?php echo $productItem['link'] ?>"><img src="<?php echo $productItem['image_path'] ?>" alt="img"></a></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>
                <div class="col-2 tool-status">
                    <ul class="list-inline">
                        <?php echo $this->getStatusHtml($designItem['status']) ?>
                        <li class="tool-link text-right"><a href="#"><i class="fas fa-share-square"></i></a></li>
                    </ul>
                </div>

            </div>

        <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
