<?php
/** @var $this Figures_Dashboard_Block_Dashboard_DesignManagement */

$designsData = $this->getDesignData();
//echo '<pre>';
//print_r($designsData);
//echo '</pre>';
//die();
?>
<?php if ($designsData) : ?>
    <div id="content_design_management" class="content_main" style="display: none;">
    <?php foreach ($designsData as $designItem) : ?>
        <div class="container">
            <img style="width:100px" src="<?php echo $designItem['image_path'] ?>">
            <label> <?php echo $designItem['status'] ?></label>
            <label> <?php echo $designItem['char_name'] ?></label>
        </div>


    <?php endforeach; ?>
    </div>
<?php endif; ?>

<div class="tools">

    <div class="tool row">
        <div class="col-2 tool-img">
            <ul>
                <li>
                    <label class="customcheck">
                        <input type="checkbox" checked="checked">
                        <span class="checkmark"></span>
                    </label>
                </li>
                <li class="img-full"><img class="float-right" src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt=""></li>
            </ul>
        </div>
        <div class="col-2 tool-about">
            <h2>Name</h2>
            <h3>Description</h3>
            <h4>tags</h4>
            <ul class="list-inline">
                <li class="list-inline-item">dxedsd</li>
                <li class="list-inline-item">axsdds</li>
                <li class="list-inline-item">nxdsds</li>
            </ul>
        </div>
        <div class="col-3 tool-sales">
            <h2>Sales</h2>
            <h3>X times</h3>
            <br>
            <h2>Commissions</h2>
            <h3>X USD</h3>
        </div>
        <div class="col-3 tool-products">
            <ul>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
                <li><img src="http://3.bp.blogspot.com/-4Wn--0A_nms/TWDh7al31xI/AAAAAAAAIIQ/6dhWOQeGw9M/s1600/Optical-illusion.jpg" alt="img"></li>
            </ul>
        </div>
        <div class="col-2 tool-status">
            <ul class="list-inline">
                <li>Pending</li>
                <li>Accepted</li>
                <li class="text-accept">Product Created</li>
                <li class="text-not-accept">Rejected</li>
                <li class="tool-link text-right"><a href="#"><i class="fas fa-share-square"></i></a></li>
            </ul>
        </div>

    </div>

</div>
