<div id="content_stats" class="content_main">
    <div class="statistics">

        <ul class="nav nav-tabs">
            <li class="nav-link"><a data-toggle="tab" href="#menu-credit" class="active show">Credit</a></li>
            <li class="nav-link"><a data-toggle="tab" href="#menu-sales">Sales</a></li>
        </ul>

        <div class="tab-content">
            <div id="menu-credit" class="tab-pane fade active show">
                <div class="container credit">
                    <div class="row">
                        <div class="offset-4 col-4 credit__title">
                            <h2>Credit</h2>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="offset-lg-1 col-lg-3 col-12">
                            <select id="creditFilter" class="form-control">
                                <option value="all">All Statuses</option>
                                <option value="not_paid">Comission not paid</option>
                                <option value="paid">Comission paid</option>
                            </select>
                        </div>
                        <div class="col-lg-3 col-12">
                            <input id="creditDateFrom" type="date" class="form-control" placeholder="From">
                        </div>
                        <div class="col-lg-3 col-12">
                            <input id="creditDateTo" type="date" class="form-control" placeholder="To">
                        </div>
                        <div class="col-lg-1 col-12">
                            <button class="btn btn-info" onclick="getCreditData(<?php echo $this->_customer->getId()?>)">Show</button>
                        </div>
                    </div>
                    <div id="creditList" class="tools">
                    </div>
                </div>
            </div>

            <div id="menu-sales" class="tab-pane fade">
                <div class="container sales">
                    <div class="row">
                        <div class="offset-4 col-4 col-auto">
                            <h2>Sales</h2>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="offset-lg-1 col-lg-3 col-12">
                            <select id="salesFilter" class="form-control">
                                <option value="all">All Statuses</option>
                                <option value="not_paid">Comission not paid</option>
                                <option value="paid">Comission paid</option>
                            </select>
                        </div>
                        <div class="col-lg-3 col-12">
                            <input id="salesDateFrom" type="date" class="form-control" placeholder="From">
                        </div>
                        <div class="col-lg-3 col-12">
                            <input id="salesDateTo" type="date" class="form-control" placeholder="To">
                        </div>
                        <div class="col-lg-1 col-12">
                            <button class="btn btn-info" onclick="getSalesData(<?php echo $this->_customer->getId()?>)">Show</button>
                        </div>
                    </div>
                    <div id="salesList" class="tools">
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>