<?php
/** $this Figures_Artist_Block_Workshop */
?>
<!--Form Tittle-->
<div class="page-title">
    <h2><?php echo $this->__('Add an new artwork') ?></h2>
</div>
<!--Form Information-->
<form id="person-form-validate" method="POST" enctype="multipart/form-data" action="/figures_artist/workshop/save">
    <div class="fieldset">
        <ul class="form-list">
            <li class="fields">
                <div class="artist_name">
                    <div class="field artist_name">
                        <div class="input-box">
                            <input type="hidden" class="input-text required-entry" maxlength="255" title="Nickname" value="<?php echo $this->getArtistNickname() ?>" name="artist_name" id="artist_name">
                        </div>
                    </div>
                    <div class="field char_name">
                        <label for="char_name"><em>*</em><?php echo $this->__('Character name')?></label>
                        <div class="input-box">
                            <input type="text" class="input-text" maxlength="255" title="Character name" value="" name="char_name" id="char_name">
                        </div>
                    </div>
                </div>
            </li>
            <li class="fields">
                <div class="additional_data">
                    <div class="field description">
                        <label class="required" for="description"><em>*</em><?php echo $this->__('Description')?></label>
                        <div class="input-box">
                            <input type="text" class="input-text required-entry" maxlength="255" title="description" value="" name="description" id="description">
                        </div>
                    </div>
                    <div class="field tags">
                        <label for="tags"><?php echo $this->__('Tags (Press Enter to submit)')?></label>
                        <ul id="submittedTags"></ul>

                            <input type="hidden" class="input-text" maxlength="255" title="description" value="" name="tags" id="tags">

                    </div>
                    <div class="field ws_image">
                        <label for="ws_image"><?php echo $this->__('Browse') ?></label>
                        <div class="input-box">
                            <input id="ws_image" name="ws_image" type="file"/>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <!--Button & Link-->
    <div class="buttons-set">
        <p class="required">* <?php echo $this->__('Required Fields')?></p>
        <p class="back-link"><a class="back-link" href="<?php echo $this->getBaseUrl();?>"><small>&laquo;</small>Back</a></p>
        <button class="button" title="Submit" type="submit"><span><span><?php echo $this->__('Submit')?></span></span></button>
    </div>
</form>

<script type="text/javascript">
    jQuery('#submittedTags').tagit({
        singleField: true,
        singleFieldNode: jQuery('#tags')
    });
</script>