<?php

?>

<div class="account text-center">
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="form-signin">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <ul class="list-inline">
            <li><h1>Log In</h1></li>
            <li><h2>Don't have an account? <a href="<?php echo $this->getUrl('customer/account/create') ?>">Sign Up</a></h2></li>
            <li><label for="inputEmail" class="sr-only">Email address</label></li>
            <li>
                <input type="email" id="email" name="login[username]" class="form-control" placeholder="Email" required autofocus>
            </li>
            <li>
                <label for="inputPassword" class="sr-only">Password</label>
                <input type="password" id="pass" name="login[password]" class="form-control" placeholder="Password" required>
            </li>
            <li>&nbsp;</li>
            <li>
<!--                <button type="submit" class="button" title="--><?php //echo $this->quoteEscape($this->__('Login')) ?><!--" name="send" id="send2"><span><span>--><?php //echo $this->__('Login') ?><!--</span></span></button>-->
                <button class="btn btn-lg btn-primary btn-block btn-info" type="submit" name="send" id="send2">Log in</button>
            </li>
            <li class="text-left remember">
                <input id="check-me" type="checkbox" value="remember-me"><label for="check-me">Remember Me</label>
                <a class="float-right" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>">Forgot password?</a>
            </li>
            <li><p class="title">Or Log In with</p></li>
            <li class="text-left contacts">
                <a class="float-left"> <i class="fa fa-facebook"></i> Facebook</a>
                <a class="float-right"> <i class="fa fa-google"></i> Google</a>
            </li>
            <li>&nbsp;</li>
        </ul>
    </form>
</div>

<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('login-form', true);
    //]]>
</script>