<?php
/** @var $this Figures_Dashboard_Block_Dashboard */
?>
<?php if ($this->isLoggedIn()) : ?>
<div class="wrapper">
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3>Bootstrap Sidebar</h3>
            <strong>BS</strong>
        </div>

        <ul class="list-unstyled components">
            <li id="menu-home" class="active"  onclick="menuToggle(this);">
                <a href="#Home">
                    <i class="fas fa-home"></i>
                    Home
                </a>
            </li>
            <li id="menu-design" onclick="menuToggle(this);">
                <a href="#Design">
                    <i class="fas fa-tshirt"></i>
                    Design
                </a>
            </li>
            <li id="menu-dash" onclick="menuToggle(this);">
                <a href="#Dashboard">
                    <i class="fas fa-tachometer-alt"></i>
                    Dashboard
                </a>
            </li>
            <li id="menu-stats" onclick="menuToggle(this);">
                <a href="#Statistics">
                    <i class="fas fa-chart-line"></i>
                    Statistics
                </a>
            </li>
            <li id="menu-tools" onclick="menuToggle(this);">
                <a href="#Tools">
                    <i class="fas fa-lightbulb"></i>
                    Tips & Tools
                </a>
            </li>
            <div class="components__bottom">
                <li id="menu-account" onclick="menuToggle(this);">
                    <a href="#Account">
                        <i class="fas fa-user-alt"></i>
                        Account
                    </a>
                </li>
                <li id="menu-eng" onclick="menuToggle(this);">
                    <a href="#English">
                        <i class="fas fa-language"></i>
                        English
                    </a>
                </li>
                <li><hr></li>
                <li id="menu-logout" onclick="menuToggle(this);">
                    <a href="#Logout">
                        <i class="fas fa-sign-out-alt"></i>
                        Logout
                    </a>
                </li>
            </div>
        </ul>

    </nav>

    <!-- Page Content  -->
    <div id="content">

        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">

                <button type="button" id="sidebarCollapse" class="btn btn-info">
                    <i class="fas fa-align-left"></i>
                    <span>Toggle Sidebar</span>
                </button>
                <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-align-justify"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="nav navbar-nav ml-auto">
                        <li>Hello, Nickname</li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div id="content_home" class="content_main">
                <h1>Home</h1>
            </div>
            <?php echo $this->getChildHtml('customer_dashboard_design'); ?>
            <?php echo $this->getChildHtml('customer_dashboard_totals'); ?>
                <?php echo $this->getChildHtml('customer_dashboard_stats'); ?>
        </div>
    </div>
</div>
<?php endif; ?>
