<?php
$customer = $this->getCustomerInfo();
$editableData = $this->getEditableData();
?>
<div class="content-header-floating" style="text-align:right;padding-top:10px;padding-bottom:10px;display: block">
    <button class="scalable back" type="button" style="margin-right:10px" onclick="goBack()">Back</button>
    <button class="scalable" type="button" onclick="setStatus('Pending')" id="pending_btn">Review</button>
    <button class="scalable success" type="button" style="margin-right:10px" onclick="setStatus('Accepted')" id="accept_btn">Accept</button>
    <button class="scalable delete" type="button" onclick="setStatus('Declined')" id="decline_btn">Decline</button>
</div>
<div class="side-col">
    <h3>Progress</h3>
    <?php if ($editableData['status'] != 'Declined') : ?>
        <div class="header-progress-container">
            <ol class="header-progress-list">
                <li id="pg_check" class="header-progress-item done">Check</li>
                <li id="pg_accept" class="header-progress-item done">Accept</li>
                <li id="pg_accept" class="header-progress-item todo">Product</li>
            </ol>
        </div>
    <?php else : ?>
        <em style="margin-left:5px">Declined</em>
    <?php endif; ?>
        <h3>Operations</h3>
        <ul class="tabs">
            <li style="cursor: pointer"><a class="tab-item-link">View info</a></li>
            <li style="cursor: pointer"><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editProducts') . 'id/' . $editableData['id'] ?>" class="tab-item-link">Product creation</a></li>
        </ul>
</div>
<div class="main-col">
    <div class="entry-edit">
        <div id="info">
            <div class="entry-edit-head" style="height:18px !important;"><h4>Artist info</h4></div>
            <fieldset>
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td style="padding-right: 100px">
                            <div>
                                <?php echo $this->__('Customer Id:'); ?>
                                <a href="<?php echo $customer['bo_link'] ?>" style="font-weight:bold;"><?php echo $customer['customer_id'] ?></a>
                            </div>
                            <div style="margin-top:20px">
                                <?php echo $this->__('NickName:'); ?>
                                <label style="font-weight:bold;"><?php echo $customer['nickname'] ?></label>
                            </div>
                        </td>
                        <td style="padding-right: 10px">
                            <em>More info will be after partner cabinet implementation</em>
                        </td>
                    </tr>
                </table>
            </fieldset>
        </div>

        <div id="proposed">
            <div class="entry-edit-head" style="height:18px !important;"><h4>Proposed Info</h4></div>
                <fieldset id="proposed_info">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td>
                                <img src="<?php echo $customer['image'] ?>" width='500px'>
                            </td>
                        </tr>
                        <tr>
                            <td style="padding-top: 10px">
                                <a target="_blank" rel="noopener noreferrer" href="<?php echo $customer['image'] ?>">Download full version</a>
                            </td>
                        </tr>
                    </table>
                    <div style="padding-top: 20px">
                        <p style="font-weight:bold;">Description</p>
                        <input type="text" class="input-text required-entry" maxlength="255" title="Description" value="<?php echo $editableData['description'] ?>" name="description" id="description" style="width: 100%;">
                        <p style="font-weight:bold; padding-top:10px">Tags</p>
                        <input type="text" class="input-text required-entry" maxlength="255" title="Tags" value="<?php echo $editableData['tags'] ?>" name="tags" id="tags" style="width: 100%;">
                    </div>
                    <div style="padding-top:20px; text-align:right">
                        <button id="saveGeneral" class="scalable" type="button" onclick="saveGeneralData()">Save general info</button>
                    </div>
                </fieldset>
        </div>
    </div>
</div>

<script type="text/javascript">
    var rowId = '<?php echo $editableData['id'] ?>';
    var currentStatus = '<?php echo $editableData['status'] ?>';

    refreshButtons();

    function saveGeneralData() {
        var url = '<?php echo $this->getUrl('adminhtml/artist_workshop/saveGeneral') ?>';

        var description = document.getElementById('description').value;
        var tags = document.getElementById('tags').value;
        new Ajax.Request(url, {
            parameters: {isAjax: 1, method: 'POST', description:description, tags:tags, id:rowId},
            onFailure: function() {
                alert('Save failed');
            },
            onSuccess: function() {}
        });
    }

    function setStatus(status) {
        var url = '<?php echo $this->getUrl('adminhtml/artist_workshop/saveStatus') ?>';

        new Ajax.Request(url, {
            parameters: {method: 'POST', status:status, id:rowId},
            onFailure: function() {
                alert('Save failed');
            },
            onSuccess: function() {
                currentStatus = status;
                refreshButtons();
            }
        });
    }

    function refreshButtons() {
        var accept = document.getElementById('accept_btn');
        var decline = document.getElementById('decline_btn');
        var review = document.getElementById('pending_btn');

        if (currentStatus === 'Pending') {
            accept.style.display = 'inline-block';
            decline.style.display = 'inline-block';
            review.style.display = 'none';
        } else {
            accept.style.display = 'none';
            decline.style.display = 'none';
            review.style.display = 'inline-block';
        }
    }

    function goBack() {
        location = '<?php echo $this->getUrl('adminhtml/artist_workshop/index') ?>';
    }
</script>
