<?php
/** @var $this Figures_Artist_Block_Adminhtml_Workshop_Forms_Products */

$customer = $this->getCustomerInfo();
$editableData = $this->getEditableData();

$proposedFormCategories = $this->getProposedFormCategories();
$genreItemCategories = $this->getGenreItemCategories();

?>
<div class="content-header-floating" style="text-align:right;padding-top:10px;padding-bottom:10px;padding-right:10px;display: block">
    <button class="scalable back" type="button" style="margin-right:10px" onclick="goBack()">Back</button>
    <?php if ($proposedFormCategories) : ?>
        <button class="scalable" type="button" onclick="submitAll()" id="pending_btn">Create products</button>
    <?php endif; ?>
</div>
<div class="side-col">
    <h3>Progress</h3>
    <?php if ($editableData['status'] != 'Declined') : ?>
        <div class="header-progress-container">
            <ol class="header-progress-list">
                <li id="pg_check" class="header-progress-item done">Check</li>
                <li id="pg_accept" class="header-progress-item done">Accept</li>
                <li id="pg_accept" class="header-progress-item done">Product</li>
            </ol>
        </div>
    <?php else : ?>
        <em style="margin-left:5px">Declined</em>
    <?php endif; ?>
    <h3>Operations</h3>
    <ul class="tabs">
        <li style="cursor: pointer"><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editGeneral') . 'id/' . $editableData['id'] ?>" class="tab-item-link">View info</a></li>
        <li style="cursor: pointer"><a class="tab-item-link">Product creation</a></li>
        <li style="cursor: pointer"><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editCreated') . 'id/' . $editableData['id'] ?>" class="tab-item-link">Created products</a></li>
    </ul>
</div>
<div id="product_block" class="main-col">
    <div id="productForm" class="entry-edit">
        <form id="productFormArea" class="entry-edit" method="POST" enctype="multipart/form-data" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/artist_workshop/createProduct") ?>">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" name="artist_id" value="<?php echo $customer['customer_id'] ?>" />
            <input type="hidden" name="work_id" value="<?php echo $editableData['id'] ?>" />
                <div id="productForm" class="entry-edit">
                    <?php if (!$proposedFormCategories) : ?>
                        <div id="info">
                            <fieldset>
                                <p>Looks like you hasn't products to create :(</p>
                                <p>Dont worry, check</p>
                                <p><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editGeneral') . 'id/' . $editableData['id'] ?>">General info</a> -> Form Categories</p>
                                <p><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editCreated') . 'id/' . $editableData['id'] ?>">Or maybe you already created this products?</a></p>
                            </fieldset>
                        </div>
                    <?php endif; ?>
                    <?php foreach ($proposedFormCategories as $proposedFormCategory) : ?>
                        <div id="info">
                            <div class="entry-edit-head" style="height:18px !important;"><h4>Add product (FORM # <?php echo $proposedFormCategory['id'] ?>)</h4></div>
                            <fieldset>
                                <table cellspacing="0" class="form-list">
                                    <tr>
                                        <h5>Category:</h5>
                                        <td style="padding-right: 100px">
                                            <div>
                                                <p><?php echo $this->__('Physical form:'); ?></p>
                                                    <select id="form_old>" name="form_old_<?php echo $proposedFormCategory['id'] ?>" disabled>
                                                        <option value="<?php echo $proposedFormCategory['id'] ?>"><?php echo $proposedFormCategory['name']; ?></option>
                                                    </select>
                                                <p style="margin:0"><?php echo $this->__('Custom Name (Not allowed):'); ?></p>
                                                <p style="margin:0">---</p>
                                            </div>
                                        </td>
                                        <td style="padding-right: 100px">
                                            <div>
                                                <p><?php echo $this->__('Genre:'); ?></p>
                                                <?php if ($genreCategories = $this->getGenreCategories($proposedFormCategory['id'])) :?>
                                                    <select id="genre_old_<?php echo $proposedFormCategory['id'] ?>" name="genre_old_<?php echo $proposedFormCategory['id'] ?>"
                                                            data-id="<?php echo $proposedFormCategory['id'] ?>"
                                                            onchange="loadFandomCategories(this)" class="genre_select" >
                                                        <option disabled selected value> -- select an option -- </option>
                                                        <?php foreach ($genreCategories as $category) : ?>
                                                            <option value="<?php echo $category['id'] ?>"><?php echo $category['name']; ?></option>
                                                        <?php endforeach; ?>
                                                    </select>
                                                <?php else : ?>
                                                    <p style="margin:0">---</p>
                                                <?php endif; ?>
                                                <p style="margin:0"><?php echo $this->__('Custom Name:'); ?></p>
                                                <input type="text" class="input-text" maxlength="255" title="genre" name="genre_<?php echo $proposedFormCategory['id'] ?>" id="genre" style="width:100%;margin-top:5px;">
                                            </div>
                                        </td>
                                        <td style="padding-right: 100px">
                                            <div>
                                                <p><?php echo $this->__('Fandom:'); ?></p>
                                                <?php if ($genreItemCategories) :?>
                                                    <select id="genre_item_old_<?php echo $proposedFormCategory['id'] ?>" name="genre_item_old_<?php echo $proposedFormCategory['id'] ?>">
                                                        <option disabled selected value> -- select an option -- </option>
                                                    </select>
                                                <?php else : ?>
                                                    <p style="margin:0">---</p>
                                                <?php endif; ?>
                                                <p style="margin:0"><?php echo $this->__('Custom Name:'); ?></p>
                                                <input type="text" class="input-text" maxlength="255" title="genre_item" name="genre_item_<?php echo $proposedFormCategory['id'] ?>" id="genre_item" style="width:100%;margin-top:5px;">
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding-right: 100px;padding-top:20px">
                                            <h5>Product:</h5>
                                            <div>
                                                <p style="margin:0"><?php echo $this->__('Title:'); ?></p>
                                                <input type="text" class="input-text" maxlength="255" title="title" name="title_<?php echo $proposedFormCategory['id'] ?>" id="title" style="width:100%;margin-top:5px;"
                                                value="<?php echo $editableData['char_name'] ?>">
                                            </div>
                                        </td>
                                        <td style="padding-right: 100px;padding-top:40px">
                                            <div>
                                                <p style="margin:0"><?php echo $this->__('Price:'); ?></p>
                                                <input type="text" class="input-text" maxlength="255" title="price" name="price_<?php echo $proposedFormCategory['id'] ?>" id="price" style="width:100%;margin-top:5px;">
                                            </div>
                                        </td>
                                        <td style="padding-right: 100px;padding-top:40px">
                                            <div>
                                                <p style="margin:0"><?php echo $this->__('Image:'); ?></p>
                                                <input id="ws_image" class="product_image" name="ws_image_<?php echo $proposedFormCategory['id'] ?>" type="file" data-id="<?php echo $proposedFormCategory['id'] ?>"/>
                                            </div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="padding-right: 100px;padding-top:40px">
                                            <div>
                                                <p style="margin:0"><?php echo $this->__('Main tag:'); ?></p>
                                                <input type="text" class="input-text" maxlength="255" name="main_tag_<?php echo $proposedFormCategory['id'] ?>"
                                                       id="title" style="width:100%;margin-top:5px;" value="<?php echo $editableData['main_tag'] ?>">
                                            </div>
                                        </td>
                                        <td style="padding-right: 100px;padding-top:40px">
                                            <div>
                                                <p style="margin:0"><?php echo $this->__('Tags:'); ?></p>
                                                <input type="text" class="input-text" maxlength="255" name="tags_<?php echo $proposedFormCategory['id'] ?>"
                                                       id="tags" style="width:100%;margin-top:5px;" value="<?php echo $editableData['tags'] ?>">
                                            </div>
                                        </td>
                                        <td style="padding-right: 100px;padding-top:40px">
                                            <div>
                                                <p style="margin:0"><?php echo $this->__('Description:'); ?></p>
                                                <textarea  maxlength="255" name="description_<?php echo $proposedFormCategory['id'] ?>"
                                                           id="description" style="width:100%;margin-top:5px;"><?php echo $editableData['description'] ?></textarea>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                                <div id="loadedImageBlock_<?php echo $proposedFormCategory['id'] ?>" style="display:none;padding-top:20px;">
                                    <h3>Loaded image:</h3>
                                    <img id="displayLoaded_<?php echo $proposedFormCategory['id'] ?>" src="#" alt="Loaded image" />
                                </div>
                            </fieldset>
                        </div>
                    <?php endforeach; ?>
                </div>
        </form>

    </div>
</div>
<script type="text/javascript">
    $j = jQuery.noConflict();
    var fandomSelect;

    function submitAll() {
        editForm = new varienForm('productFormArea', '');
        editForm.submit();
    }

    $j(".product_image").change(function() {
        readURL(this);
    });

    function readURL(input) {

        var id = $j(input).data("id");
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $j('#displayLoaded_' + id).attr('src', e.target.result);
                $j('#loadedImageBlock_' + id).show();
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function loadFandomCategories(select) {
        var id = $j(select).data("id");
        fandomSelect = $j('#genre_item_old_' + id);
        fandomSelect.prop("disabled", true);
        fandomSelect
            .find('option')
            .remove();

        $j.get(
            '<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/artist_workshop/getFandomCategories") ?>',
            {
                genre_cat_id: select.value
            },
            onloadFandomCategoriesSuccess
        );

        fandomSelect.prop("disabled", false);
    }

    function onloadFandomCategoriesSuccess(data)
    {
        if (data == '[]') {
        } else {
            console.log(data);
            var options = JSON.parse(data);
            $j.each(options, function (index, options) {
                console.log(fandomSelect);
                fandomSelect.append('<option value="' + options.id + '">' + options.name +'</option>');
            });
        }
    }
</script>