<?php
/** @var $this Figures_Artist_Block_Adminhtml_Workshop_Forms_Products */

$customer = $this->getCustomerInfo();
$editableData = $this->getEditableData();

$formCategories = $this->getFormCategories();
$genreCategories = $this->getGenreCategories();
$genreItemCategories = $this->getGenreItemCategories();

?>
<div class="content-header-floating" style="text-align:right;padding-top:10px;padding-bottom:10px;padding-right:10px;display: block">
    <button class="scalable back" type="button" style="margin-right:10px" onclick="goBack()">Back</button>
    <button class="scalable" type="button" onclick="submitAll()" id="pending_btn">Add product</button>
<!--    <button style="margin-left: 50px" class="scalable" type="button" onclick="saveAll()" id="pending_btn">Save all</button>-->
</div>
<div class="side-col">
    <h3>Progress</h3>
    <?php if ($editableData['status'] != 'Declined') : ?>
        <div class="header-progress-container">
            <ol class="header-progress-list">
                <li id="pg_check" class="header-progress-item done">Check</li>
                <li id="pg_accept" class="header-progress-item done">Accept</li>
                <li id="pg_accept" class="header-progress-item done">Product</li>
            </ol>
        </div>
    <?php else : ?>
        <em style="margin-left:5px">Declined</em>
    <?php endif; ?>
    <h3>Operations</h3>
    <ul class="tabs">
        <li style="cursor: pointer"><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editGeneral') . 'id/' . $editableData['id'] ?>" class="tab-item-link">View info</a></li>
        <li style="cursor: pointer"><a class="tab-item-link">Product creation</a></li>
        <li style="cursor: pointer"><a href="<?php echo $this->getUrl('adminhtml/artist_workshop/editCreated') . 'id/' . $editableData['id'] ?>" class="tab-item-link">Created products</a></li>
    </ul>
</div>
<div id="product_block" class="main-col">
    <div id="productForm" class="entry-edit">
        <form id="productFormArea" class="entry-edit" method="POST" enctype="multipart/form-data" action="<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/artist_workshop/createProduct") ?>">
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <input type="hidden" name="artist_id" value="<?php echo $customer['customer_id'] ?>" />
            <input type="hidden" name="work_id" value="<?php echo $editableData['id'] ?>" />
                <div id="productForm" class="entry-edit">
                    <div id="info">
                        <div class="entry-edit-head" style="height:18px !important;"><h4>Add product</h4></div>
                        <fieldset>
                            <table cellspacing="0" class="form-list">
                                <tr>
                                    <h5>Category:</h5>
                                    <td style="padding-right: 100px">
                                        <div>
                                            <p><?php echo $this->__('Physical form:'); ?></p>
                                            <?php if ($formCategories) :?>
                                                <select id="form_old" name="form_old">
                                                    <?php foreach ($formCategories as $category) : ?>
                                                        <option value="<?php echo $category['id'] ?>"><?php echo $category['name']; ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            <?php else : ?>
                                                <p style="margin:0">---</p>
                                            <?php endif; ?>
                                            <p style="margin:0"><?php echo $this->__('Custom Name:'); ?></p>
                                            <input type="text" class="input-text" maxlength="255" title="form" name="form" id="form" style="width:100%;margin-top:5px;">
                                        </div>
                                    </td>
                                    <td style="padding-right: 100px">
                                        <div>
                                            <p><?php echo $this->__('Genre:'); ?></p>
                                            <?php if ($genreCategories) :?>
                                                <select id="genre_old" name="genre_old">
                                                    <?php foreach ($genreCategories as $category) : ?>
                                                        <option value="<?php echo $category['id'] ?>"><?php echo $category['name']; ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            <?php else : ?>
                                                <p style="margin:0">---</p>
                                            <?php endif; ?>
                                            <p style="margin:0"><?php echo $this->__('Custom Name:'); ?></p>
                                            <input type="text" class="input-text" maxlength="255" title="genre" name="genre" id="genre" style="width:100%;margin-top:5px;">
                                        </div>
                                    </td>
                                    <td style="padding-right: 100px">
                                        <div>
                                            <p><?php echo $this->__('Fandom:'); ?></p>
                                            <?php if ($genreItemCategories) :?>
                                                <select id="genre_item_old" name="genre_item_old">
                                                    <?php foreach ($genreItemCategories as $category) : ?>
                                                        <option value="<?php echo $category['id'] ?>"><?php echo $category['name']; ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            <?php else : ?>
                                                <p style="margin:0">---</p>
                                            <?php endif; ?>
                                            <p style="margin:0"><?php echo $this->__('Custom Name:'); ?></p>
                                            <input type="text" class="input-text" maxlength="255" title="genre_item" name="genre_item" id="genre_item" style="width:100%;margin-top:5px;">
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding-right: 100px;padding-top:20px">
                                        <h5>Product:</h5>
                                        <div>
                                            <p style="margin:0"><?php echo $this->__('Title:'); ?></p>
                                            <input type="text" class="input-text" maxlength="255" title="title" name="title" id="title" style="width:100%;margin-top:5px;">
                                        </div>
                                    </td>
                                    <td style="padding-right: 100px;padding-top:40px">
                                        <div>
                                            <p style="margin:0"><?php echo $this->__('Sku:'); ?></p>
                                            <input type="text" class="input-text" maxlength="255" title="sku" name="sku" id="sku" style="width:100%;margin-top:5px;">
                                        </div>
                                    </td>
                                    <td style="padding-right: 100px;padding-top:40px">
                                        <div>
                                            <p style="margin:0"><?php echo $this->__('Price:'); ?></p>
                                            <input type="text" class="input-text" maxlength="255" title="price" name="price" id="price" style="width:100%;margin-top:5px;">
                                        </div>
                                    </td>
                                    <td style="padding-right: 100px;padding-top:40px">
                                        <div>
                                            <p style="margin:0"><?php echo $this->__('Image:'); ?></p>
                                            <input id="ws_image" name="ws_image" type="file"/>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                            <div id="loadedImageBlock" style="display:none;padding-top:20px;">
                                <h3>Loaded image:</h3>
                                <img id="displayLoaded" src="#" alt="Loaded image" />
                            </div>
                        </fieldset>
                    </div>
                </div>
        </form>

    </div>
</div>
<script type="text/javascript">
    $j = jQuery.noConflict();

    function submitAll() {
        editForm = new varienForm('productFormArea', '');
        editForm.submit();
    }

    $j("#ws_image").change(function() {
        readURL(this);
    });

    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $j('#displayLoaded').attr('src', e.target.result);
                $j('#loadedImageBlock').show();
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>