<?php
/**
 * @var Figures_Cms_Block_Header $this
 */
$headerItems = $this->getHeaderItems();
$session = $this->getSession();
?>

<header>
    <div class="login">
        <div class="container">
            <nav class="navbar navbar-inverse pads0">
                <div class="navbar-header">
                </div>
                <ul class="nav navbar-right">
                    <?php if ($session->isLoggedIn()) : ?>
                        <li><span class="navbar-divider"> Logged as <?php echo $session->getCustomer()->getData('artist_nickname') ?></span></li>
                        <li><a href="<?php echo $this->getUrl('customer_dashboard') ?>" class="navbar-divider"> Dashboard</a></li>
                        <li><a href="<?php echo Mage::helper('customer')->getLogoutUrl() ?>"> Log Out</a></li>
                    <?php else : ?>
                        <li><a href="<?php echo $this->getUrl('customer_dashboard') ?>" class="navbar-divider"> Sell Your Art</a></li>
                        <li><a href="<?php echo $this->getUrl('customer/account/login') ?>" class="navbar-divider"> Log In</a></li>
                        <li><a href="<?php echo $this->getUrl('customer/account/create') ?>"> Sign Up</a></li>
                    <?php endif; ?>
                </ul>
            </nav>
        </div>
    </div>

    <div class="search">
        <div class="container">
            <div class="blog-header py-3">
                <div class="row align-items-center">
                    <div class="col-2 pt-1 col_logo">
                        <a class="navbar-brand" href="<?php echo $this->getBaseUrl() ?>">
                            <img src="<?php echo $this->getSkinUrl('images/logo.png') ?>" class="d-inline-block align-top" alt="Logotype">
                            <span class="site_name text-muted"><?php echo $this->getStoreName() ?></span>
                        </a>
                    </div>
                    <div class="col-8 col_search">
                        <div class="input-group">
                            <input id="searchText" type="text" class="form-control" placeholder="Find your thing">
                            <span class="input-group-btn">
                            <button id="search" class="btn btn-outline-secondary" type="button"><i class="fa fa-search"></i></button>
                          </span>
                        </div>
                    </div>
                    <div class="col-1 col_basket">
                        <div class="basket-product-amount">
                            <span>0</span>
                        </div>
                        <button class="btn btn-outline-secondary" type="button"><i class="fa fa-shopping-basket"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="catalogue navbar-collapse collapse show" id="navbarsExampleDefault">
        <div class="container">
            <div class="nav-scroller py-1 mb-2">
                <ul class="nav">
                    <?php foreach ($headerItems as $headerItem) : ?>
                        <li><a class="p-2 text-muted" href="<?php echo $headerItem['link'] ?>"><?php echo $headerItem['name'] ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
</header>

<?php echo $this->getChildHtml('topContainer'); ?>
