<?php
/** @var $this Figures_Catalog_Block_Product_List */

$filters = $this->getAvailableFilters();
?>
<div class="row category-header">
    <div class="col-6">
        <div id="category-list"></div>
    </div>
    <div class="col-6 text-right">
        <select id="sort_by" title="Sort by">
            <option value="default">Most relevant</option>
            <option value="price_asc">More expensive</option>
            <option value="price_desc">More cheaper</option>
        </select>
    </div>
</div>

<div class="row category">

    <?php if ($filters) : ?>
        <div class="col-2 category-sidebar">

            <?php echo $filters; ?>

            <div class="category-sidebar__prices">
                <div class="sidebar-title">
                    <p>Prices</p> <a class="sidebar__price-arrow" onclick="toggleBlock(this,'price_list')"><i class="fa fa-angle-up"></i></a>
                </div>
                <ul id="price_list" class="sidebar-list list-inline">
                    <li>
                        <label for="min_price">From</label>
                        <input id="min_price" class="form-control" type="number" min="0" name="min_price" title="input min price" value="0">
                    </li>
                    <li>
                        <label for="max_price">To</label>
                        <input  id="max_price" class="form-control" type="number" min="0" name="max_price" title="input max price" value="0">
                    </li>
                    <li>
                        <button class="btn btn-outline-primary" style="width: 100%" onclick="processPriceFilter()">OK</button>
                    </li>
                </ul>
            </div>
        </div>
    <?php endif; ?>

    <div class="col-10 category-products"></div>

</div>

<div class="row category-footer">
    <div class="col-10 offset-2">
        <nav class="float-right">
            <ul id="pager" class="pagination">
<!--                <li class="page-item"><a class="page-link" href="#">Previous</a></li>-->
<!--                <li class="page-item"><a class="page-link" href="#">1</a></li>-->
<!--                <li class="page-item"><a class="page-link" href="#">2</a></li>-->
<!--                <li class="page-item"><a class="page-link" href="#">3</a></li>-->
<!--                <li class="page-item"><a class="page-link" href="#">Next</a></li>-->
            </ul>
        </nav>
    </div>
</div>
<input type="hidden" id="category" value="<?php echo $this->getCategoryId() ?>">

<hr>

<div id="loader" class="loading" style="display:none;">Loading&#8230;</div>
