
<div class="row category-header">
    <div class="col-6">
        <h2>Boyfriend Greeting Cards <span>52269 results</span></h2>
    </div>
    <div class="col-6 text-right">
        <select title="Sort by">
            <option value="1">Most relevant</option>
            <option value="2">More expensive</option>
            <option value="3">More cheaper</option>
        </select>
    </div>
</div>

<div class="row category">

    <div class="col-2 category-sidebar">
        <div class="category-sidebar__department">
            <div class="sidebar-title">
                <p>Department</p> <a class="sidebar__department-arrow" onclick="toggleBlock(this,'department_list')"><i class="fa fa-angle-up"></i></a>
            </div>
            <ul id="department_list" class="sidebar-list list-inline">
                <li>All departments</li>
                <li>Men's</li>
                <li>Women's</li>
                <li>Kids</li>
                <li>Device Cases</li>
                <li>Wall Art</li>
                <li>Home decor</li>
                <li>Stationary</li>
                <li>Bags</li>
            </ul>
        </div>

        <div class="category-sidebar__product">
            <div class="sidebar-title">
                <p>Product</p> <a class="sidebar__product-arrow" onclick="toggleBlock(this,'product_list')"><i class="fa fa-angle-up"></i></a>
            </div>
            <ul id="product_list" class="sidebar-list list-inline">
                <li>All stationary</li>
                <li>Greeting cards</li>
                <li>Postcards</li>
                <li>Stickers</li>
                <li>Spiral notebooks</li>
            </ul>
        </div>
    </div>

    <div class="col-10 category-products">

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

        <div class="category-product-card">
            <div class="category-product-image">
                <img src="/img/logo.jpg">
            </div>
            <div class="category-product-info">
                <h4>$99.99</h4>
                <h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad amet architecto ducimus ipsa iure, molestiae numquam obcaecati optio perferendis quidem quis quod quos ratione sequi similique sit ullam vero voluptates.</h5>
                <h6>by <a href="#">Author</a></h6>
            </div>
        </div>

    </div>

</div>

<div class="row category-footer">
    <div class="col-10 offset-2">
        <nav aria-label="Page navigation example" class="float-right">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>
    </div>
</div>

<hr>

<script>
    function toggleBlock(block,slide) { "use strict";
        jQuery("#"+slide).slideToggle("slow");
        jQuery(block).find('i').toggleClass('icon-rotate');
    }
</script>