<?php $price = $this->getPrice(); ?>
<?php $_product = $this->getProduct(); ?>
<main id="main" role="main" class="container">

<div class="row catalogue">
    <div class="col-lg-6 col-12">
        <div class="fotorama" data-nav="thumbs" data-loop="true" data-arrows="true">
            <img src="<?php echo Mage::getModel('catalog/product_media_config')->getMediaUrl( $_product->getImage()); ?>">
<!--            <img src="https://images.pexels.com/photos/443446/pexels-photo-443446.jpeg?auto=compress&cs=tinysrgb&h=350">-->
<!--            <img src="https://playdauntless.com/images/media-wallpapers/shrike-soaring-wallpaper-dauntless-2560x1600.jpg">-->
<!--            <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg">-->
        </div>
    </div>
    <div class="col-lg-6 col-12 product">
        <ul class="list-inline">
            <li class="row">
                <div class="col-3 product-author">
                    <img class="float-right" src="http://www.lte-esafety.co.uk/wp-content/uploads/2015/06/avatar.png" alt="">
                </div>
                <div class="col-3 product-author">
                    <ul class="list-inline">
                        <li><h3>Nickname</h3></li>
                        <li><span>United States of America</span></li>
                        <li><button class="btn btn-dark">Follow</button></li>
                    </ul>
                </div>
            </li>
            <li class="product-name">
                <h2><?php echo $_product->getName() ?></h2>
            </li>
            <li class="product-type">
                <span>Product Type</span>
            </li>
            <li class="product-links list-inline">
                <a href="#" class=""><i class="fa fa-link text-link"></i></a>
                <a href="#" class=""><i class="fa fa-twitter text-tw"></i></a>
                <a href="#" class=""><i class="fa fa-facebook text-fb"></i></a>
                <a href="#" class=""><i class="fa fa-google-plus text-gplus"></i></a>
                <a href="#" class=""><i class="fa fa-pinterest text-pint"></i></a>
            </li>
            <li class="product-author">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi ipsum itaque nihil rem!
                    A architecto beatae eius facilis mollitia similique sint vitae voluptatem?
                    Consequatur nobis perferendis reiciendis repellendus voluptas, voluptate.</p>
            </li>
            <li class="product-quality">
                <ul>
                    <li>Material</li>
                    <li>Height</li>
                </ul>
            </li>
            <div class="product-to-price">
                <li class="product-price">
                    <span>$<?php echo $price['dollars'] ?>
                        <?php if ($price['cents']) : ?>
                            <sup>.<?php echo $price['cents'] ?></sup>
                        <?php endif; ?>
                    </span>
                </li>
                <li class="product-buy">
                    <button onclick="location = '<?php echo $this->getAddToCartUrl($_product); ?>'" class="btn btn-primary">Add to cart</button>
                </li>
                <li class="product-delivery">
                    <span>Plus shipping | Delivery in 5-12 days</span>
                </li>
                <li class="product-like">
                    <p>
                        <span>50 <i class="fa fa-heart"></i></span> Wishlist
                        <span style="padding-left: 15px;"><i class="fa fa-share"></i></span> Share
                    </p>
                </li>
            </div>
        </ul>
    </div>
</div>

<hr>

<div class="row product-design">
    <div class="container">
        <h2>Get the design on the amazing products</h2>
        <div class="owl-carousel owl-theme">
            <div class="item">
                <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg" alt="img_design">
                <h3>IPhone Galaxy XS</h3>
                <span>$20.99</span>
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
            </div>
            <div class="item">
                <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg" alt="img_design">
                <h3>IPhone Galaxy XS</h3>
                <span>$20.99</span>
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
            </div>
            <div class="item">
                <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg" alt="img_design">
                <h3>IPhone Galaxy XS</h3>
                <span>$20.99</span>
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
            </div>
            <div class="item">
                <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg" alt="img_design">
                <h3>IPhone Galaxy XS</h3>
                <span>$20.99</span>
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
            </div>
            <div class="item">
                <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg" alt="img_design">
                <h3>IPhone Galaxy XS</h3>
                <span>$20.99</span>
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
            </div>
            <div class="item">
                <img src="http://www.conmasgracia.org/wp-content/uploads/2018/05/1.jpg" alt="img_design">
                <h3>IPhone Galaxy XS</h3>
                <span>$20.99</span>
                <div class="product-rating">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>
</main>

<script>
    jQuery(document).ready(function() {
        startOwl();
    });

    function startOwl() {
        var owl = jQuery('.owl-carousel');
        owl.owlCarousel({
            margin: 10,
            nav: true,
            dots: false,
            loop: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        })
    }

</script>